### ISSUE TITLE
Virtual Screening and De-novo generation datasets

### ISSUE THREAD

**Issue by RaulFD-creator** [valence-labs/mood-experiments#4]
Hi @cwognum,

I've read the pre-print of your work in Chemrxiv "Real-World Molecular Out-Of-Distribution: Specification and Investigation" and found it really interesting. I was wondering whether you could share the datasets for the virtual screening and/or de-novo generation experiments. If that wasn't possible, could you share the code used to generate the de-novo dataset.

Thanks beforehand!

**Comment by cwognum** [comment]
Hi @RaulFD-creator, 

Thank you for the kind words! 

All the data has been made available in a public GCP bucket at [`gs://mood-data-public`](https://storage.googleapis.com/mood-data-public/). As to your question specifically, you can find the deployment datasets here: 
  - Virtual screening: [`gs://mood-data-public/downstream_applications/virtual_screening.csv`](https://storage.googleapis.com/mood-data-public/downstream_applications/virtual_screening.csv)
  - De-novo generation: [`gs://mood-data-public/downstream_applications/optimization.csv`](https://storage.googleapis.com/mood-data-public/downstream_applications/optimization.csv)

You can click the links above to directly download the CSV files or e.g. use:
```python
import pandas as pd
df = pd.read_csv("gs://mood-data-public/downstream_applications/optimization.csv")
```

Let me know if that helps! Happy to help with any other questions.

**Comment by RaulFD-creator** [comment]
Thank you so much! That's exactly what I needed. I think that for now that's all, but if I need anything else, I'll let you know.
